/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_diegovarela;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author diego
 */
public class LAB5 extends javax.swing.JFrame {

    /**
     * Creates new form LAB5
     */
    public LAB5() {
        initComponents();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_grupo.getModel();
        modelo.addElement("X-men");
        modelo.addElement("Vengadores");
        cb_grupo.setModel(modelo);

        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_villano.getModel();
        model.addElement("The Dark Avengers");
        model.addElement("Sinister Six");
        cb_villano.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregar = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_planeta = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_altura = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cb_grupo = new javax.swing.JComboBox<>();
        tf_poder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_vengadores = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_xmen = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sp_edad1 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        cb_villano = new javax.swing.JComboBox<>();
        tf_poder1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_altura1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_darkavenger = new javax.swing.JList<>();
        jLabel26 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tf_nombre1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_sinistersix = new javax.swing.JList<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_planeta1 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jt_heroes = new javax.swing.JTree();
        jScrollPane8 = new javax.swing.JScrollPane();
        jt_villanos = new javax.swing.JTree();
        jLabel34 = new javax.swing.JLabel();
        sp_muertes = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        tf_acrcel = new javax.swing.JTextField();
        jd_poder = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_descrip = new javax.swing.JTextArea();
        tf_nivel = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_moratl = new javax.swing.JTextField();
        jb_agregarpoder = new javax.swing.JButton();
        jb_salirpoder = new javax.swing.JButton();
        jd_poderv = new javax.swing.JDialog();
        jb_salirpoder1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_descrip1 = new javax.swing.JTextArea();
        tf_nivel1 = new javax.swing.JTextField();
        tf_moratl1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jb_agregarpoder1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        popup_eliminar = new javax.swing.JPopupMenu();
        jm_agregararbol = new javax.swing.JMenuItem();
        jm_eliminar = new javax.swing.JMenuItem();
        popup_eliminar2 = new javax.swing.JPopupMenu();
        jm_agregar = new javax.swing.JMenuItem();
        jm_el = new javax.swing.JMenuItem();
        popup_sinister = new javax.swing.JPopupMenu();
        jm_agregars = new javax.swing.JMenuItem();
        jm_eliminars = new javax.swing.JMenuItem();
        popup_dark = new javax.swing.JPopupMenu();
        jm_agregard = new javax.swing.JMenuItem();
        jm_eliminard = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JPasswordField();
        tf_user = new javax.swing.JTextField();
        jb_entrar = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Agregar superheroe y villanos");

        jLabel5.setText("Superoheroes");

        jLabel6.setText("Villanos");

        jLabel7.setText("Nombre:");

        jLabel9.setText("Edad:");

        jLabel10.setText("Planeta:");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel());
        sp_edad.setValue(20
        );

        jLabel12.setText("Altura:");

        jLabel15.setText("Grupos:");

        cb_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        tf_poder.setText("Agregar superpoder");
        tf_poder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_poderMouseClicked(evt);
            }
        });

        jl_vengadores.setModel(new DefaultListModel());
        jl_vengadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_vengadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_vengadores);

        jButton1.setText("Agregar superoheroe");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel16.setText("Vengadores");

        jl_xmen.setModel(new DefaultListModel());
        jl_xmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_xmenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_xmen);

        jLabel17.setText("X-men");

        sp_edad1.setModel(new javax.swing.SpinnerNumberModel());
        sp_edad1.setValue(20
        );

        jLabel23.setText("Grupos:");

        cb_villano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        tf_poder1.setText("Agregar superpoder");
        tf_poder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_poder1MouseClicked(evt);
            }
        });

        jLabel24.setText("Nombre:");

        jLabel25.setText("Altura:");

        jl_darkavenger.setModel(new DefaultListModel());
        jl_darkavenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_darkavengerMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jl_darkavenger);

        jLabel26.setText("Edad:");

        jButton2.setText("Agregar villano");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel27.setText("The Dark Avengers");

        jl_sinistersix.setModel(new DefaultListModel());
        jl_sinistersix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_sinistersixMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jl_sinistersix);

        jLabel28.setText("Sinister six");

        jLabel29.setText("Planeta:");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Heroes");
        jt_heroes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane7.setViewportView(jt_heroes);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Villanos");
        jt_villanos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane8.setViewportView(jt_villanos);

        jLabel34.setText("Muertes causadas:");

        jLabel35.setText("Carcel:");

        tf_acrcel.setText("                   ");

        javax.swing.GroupLayout jd_agregarLayout = new javax.swing.GroupLayout(jd_agregar.getContentPane());
        jd_agregar.getContentPane().setLayout(jd_agregarLayout);
        jd_agregarLayout.setHorizontalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel16)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel17))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_agregarLayout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_villano, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_altura1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_planeta1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)
                                        .addComponent(sp_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jd_agregarLayout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(tf_poder1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_muertes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(jd_agregarLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_acrcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel27))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarLayout.createSequentialGroup()
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_altura))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_planeta))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_agregarLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(tf_poder, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(185, 185, 185))
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(130, 130, 130))
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel4))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_agregarLayout.setVerticalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(sp_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(tf_planeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(tf_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(tf_poder1)
                                .addGap(38, 38, 38)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(cb_villano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(sp_muertes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel35)
                                    .addComponent(tf_acrcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_agregarLayout.createSequentialGroup()
                                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(tf_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarLayout.createSequentialGroup()
                                        .addComponent(tf_poder)
                                        .addGap(25, 25, 25)))
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(cb_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarLayout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)))
                        .addGap(16, 16, 16)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel14.setText("Agregar Superpoder");

        jLabel18.setText("Nivel:");

        jLabel19.setText("Descripcion:");

        ta_descrip.setColumns(20);
        ta_descrip.setRows(5);
        jScrollPane3.setViewportView(ta_descrip);

        jLabel21.setText("Mortal:");

        jb_agregarpoder.setText("Agregar");
        jb_agregarpoder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarpoderMouseClicked(evt);
            }
        });

        jb_salirpoder.setText("Salir");
        jb_salirpoder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirpoderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_poderLayout = new javax.swing.GroupLayout(jd_poder.getContentPane());
        jd_poder.getContentPane().setLayout(jd_poderLayout);
        jd_poderLayout.setHorizontalGroup(
            jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_poderLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jb_agregarpoder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_poderLayout.createSequentialGroup()
                .addGroup(jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_poderLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(jd_poderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nivel)
                            .addGroup(jd_poderLayout.createSequentialGroup()
                                .addGroup(jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_salirpoder)
                                    .addGroup(jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_moratl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(173, 173, 173))
        );
        jd_poderLayout.setVerticalGroup(
            jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_poderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addGroup(jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_moratl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_poderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_agregarpoder)
                    .addComponent(jb_salirpoder))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jb_salirpoder1.setText("Salir");
        jb_salirpoder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirpoder1MouseClicked(evt);
            }
        });

        ta_descrip1.setColumns(20);
        ta_descrip1.setRows(5);
        jScrollPane6.setViewportView(ta_descrip1);

        jLabel30.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel30.setText("Agregar Superpoder");

        jb_agregarpoder1.setText("Agregar");
        jb_agregarpoder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarpoder1MouseClicked(evt);
            }
        });

        jLabel31.setText("Nivel:");

        jLabel32.setText("Descripcion:");

        jLabel33.setText("Mortal:");

        javax.swing.GroupLayout jd_podervLayout = new javax.swing.GroupLayout(jd_poderv.getContentPane());
        jd_poderv.getContentPane().setLayout(jd_podervLayout);
        jd_podervLayout.setHorizontalGroup(
            jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_podervLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addGroup(jd_podervLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(20, 20, 20)))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_podervLayout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addGroup(jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_podervLayout.createSequentialGroup()
                            .addComponent(jb_agregarpoder1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_podervLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30))
                            .addGroup(jd_podervLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nivel1)
                                    .addGroup(jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jb_salirpoder1)
                                        .addGroup(jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_moratl1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGap(91, 91, 91)))
        );
        jd_podervLayout.setVerticalGroup(
            jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_podervLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel31)
                .addGap(26, 26, 26)
                .addComponent(jLabel32)
                .addGap(65, 65, 65)
                .addComponent(jLabel33)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_podervLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel30)
                    .addGap(33, 33, 33)
                    .addComponent(tf_nivel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)
                    .addComponent(tf_moratl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jd_podervLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_agregarpoder1)
                        .addComponent(jb_salirpoder1))
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        jm_agregararbol.setText("Agregar al arbol");
        jm_agregararbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_agregararbolActionPerformed(evt);
            }
        });
        popup_eliminar.add(jm_agregararbol);

        jm_eliminar.setText("eliminar");
        jm_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_eliminarMouseClicked(evt);
            }
        });
        jm_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_eliminarActionPerformed(evt);
            }
        });
        popup_eliminar.add(jm_eliminar);

        jm_agregar.setText("Agregar al arbol");
        jm_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_agregarActionPerformed(evt);
            }
        });
        popup_eliminar2.add(jm_agregar);

        jm_el.setText("Eliminar");
        jm_el.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_elActionPerformed(evt);
            }
        });
        popup_eliminar2.add(jm_el);

        jm_agregars.setText("Agregar al arbol\n");
        popup_sinister.add(jm_agregars);

        jm_eliminars.setText("Eliminar\n");
        jm_eliminars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_eliminarsActionPerformed(evt);
            }
        });
        popup_sinister.add(jm_eliminars);

        jm_agregard.setText("Agregar al arbol");
        popup_dark.add(jm_agregard);

        jm_eliminard.setText("Eliminar");
        jm_eliminard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_eliminardActionPerformed(evt);
            }
        });
        popup_dark.add(jm_eliminard);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setText("User:");

        jLabel3.setText("Password:");

        tf_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_userActionPerformed(evt);
            }
        });

        jb_entrar.setText("ENTRAR");
        jb_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_entrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_pass)
                                .addComponent(tf_user))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jb_entrar)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jb_entrar)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_userActionPerformed

    private void jb_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_entrarMouseClicked
        // TODO add your handling code here:
        String user = "stanlee";
        String password = "spiderman99";
        if (tf_pass.getText().equals(password) && tf_user.getText().equals(user)) {
            jd_agregar.pack();
            jd_agregar.setLocationRelativeTo(null);
            jd_agregar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo entrar debido a que el usuario o la contraseña es incorrecta");
        }
    }//GEN-LAST:event_jb_entrarMouseClicked

    private void jb_agregarpoderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarpoderMouseClicked
        // TODO add your handling code here:
        Super p = new Super();
        int nivel = Integer.parseInt(tf_nivel.getText());
        if (p.getPoderes().size() <= 2) {
            if (nivel >= 1 && nivel <= 10) {
                p.getPoderes().add(new Superpoderes(Integer.parseInt(tf_nivel.getText()), ta_descrip.getText(), tf_moratl.getText()));
                tf_nivel.setText("");
                ta_descrip.setText("");
                tf_moratl.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ya no se puede crear mas superpoderes");
        }
    }//GEN-LAST:event_jb_agregarpoderMouseClicked

    private void jb_salirpoderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirpoderMouseClicked
        // TODO add your handling code here:
        jd_poder.setVisible(false);
    }//GEN-LAST:event_jb_salirpoderMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (((String) cb_grupo.getSelectedItem()).equals("X-men")) {
            DefaultListModel modelo = (DefaultListModel) jl_xmen.getModel();
            modelo.addElement(new Super(tf_nombre.getText(), (Integer) sp_edad.getValue(), tf_planeta.getText(), tf_altura.getText(), 0));
            jl_xmen.setModel(modelo);
            tf_nombre.setText("");
            sp_edad.setValue(20);
            tf_planeta.setText("");
            tf_altura.setText("");
            sp_muertes.setValue(0);

        } else if (((String) cb_grupo.getSelectedItem()).equals("Vengadores")) {
            DefaultListModel modelo = (DefaultListModel) jl_vengadores.getModel();
            modelo.addElement(new Super(tf_nombre.getText(), (Integer) sp_edad.getValue(), tf_planeta.getText(), tf_altura.getText(), 0));
            jl_vengadores.setModel(modelo);
            tf_nombre.setText("");
            sp_edad.setValue(20);
            tf_planeta.setText("");
            tf_altura.setText("");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void tf_poderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_poderMouseClicked
        // TODO add your handling code here:
        jd_poder.pack();
        jd_poder.setLocationRelativeTo(null);
        jd_poder.setVisible(true);
    }//GEN-LAST:event_tf_poderMouseClicked

    private void tf_poder1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_poder1MouseClicked
        // TODO add your handling code here:
        jd_poderv.pack();
        jd_poderv.setLocationRelativeTo(null);
        jd_poderv.setVisible(true);
    }//GEN-LAST:event_tf_poder1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (((String) cb_villano.getSelectedItem()).equals("The Dark Avengers")) {
            DefaultListModel modelo = (DefaultListModel) jl_xmen.getModel();
            modelo.addElement(new Villanos(tf_nombre.getText(), (Integer) sp_edad.getValue(), tf_planeta.getText(), tf_altura.getText(), (Integer) sp_muertes.getValue(), tf_acrcel.getText()));
            jl_sinistersix.setModel(modelo);
            tf_nombre1.setText("");
            sp_edad1.setValue(20);
            tf_planeta1.setText("");
            tf_altura1.setText("");
            sp_muertes.setValue(0);
            tf_acrcel.setText("");

        } else if (((String) cb_villano.getSelectedItem()).equals("Sinister Six")) {
            DefaultListModel modelo = (DefaultListModel) jl_vengadores.getModel();
            modelo.addElement(new Villanos(tf_nombre.getText(), (Integer) sp_edad.getValue(), tf_planeta.getText(), tf_altura.getText(), (Integer) sp_muertes.getValue(), tf_acrcel.getText()));
            jl_darkavenger.setModel(modelo);
            tf_nombre1.setText("");
            sp_edad1.setValue(20);
            tf_planeta1.setText("");
            tf_altura1.setText("");
            sp_muertes.setValue(0);
            tf_acrcel.setText("");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_salirpoder1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirpoder1MouseClicked
        // TODO add your handling code here:
        jd_poderv.setVisible(false);

    }//GEN-LAST:event_jb_salirpoder1MouseClicked

    private void jb_agregarpoder1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarpoder1MouseClicked
        // TODO add your handling code here:
        Villanos p = new Villanos();
        int nivel = Integer.parseInt(tf_nivel1.getText());
        if (p.getSpoderes().size() <= 2) {
            if (nivel >= 1 && nivel <= 10) {
                p.getSpoderes().add(new Superpoderes(Integer.parseInt(tf_nivel1.getText()), ta_descrip1.getText(), tf_moratl1.getText()));
                tf_nivel1.setText("");
                ta_descrip1.setText("");
                tf_moratl1.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ya no se puede crear mas superpoderes");
        }
    }//GEN-LAST:event_jb_agregarpoder1MouseClicked

    private void jl_vengadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_vengadoresMouseClicked
        // TODO add your handling code here:
        if (jl_vengadores.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_eliminar.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_vengadoresMouseClicked

    private void jl_xmenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_xmenMouseClicked
        // TODO add your handling code here:
        if (jl_xmen.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_eliminar2.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jl_xmenMouseClicked

    private void jm_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_eliminarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jm_eliminarMouseClicked

    private void jm_elActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_elActionPerformed
        // TODO add your handling code here:
        if (jl_xmen.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) jl_xmen.getModel();
            modelo.remove(jl_xmen.getSelectedIndex());
            jl_xmen.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");
        }
    }//GEN-LAST:event_jm_elActionPerformed

    private void jm_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_eliminarActionPerformed
        // TODO add your handling code here:
        if (jl_vengadores.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) jl_vengadores.getModel();
            modelo.remove(jl_vengadores.getSelectedIndex());
            jl_vengadores.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");
        }
    }//GEN-LAST:event_jm_eliminarActionPerformed

    private void jm_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_agregarActionPerformed
        // TODO add your handling code here:
        if (jl_xmen.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL
                    = (DefaultTreeModel) jt_heroes.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloARBOL.getRoot();

            //obtener la persona a guardar
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_xmen.getModel();
            String planeta, nombre, altura;
            int edad, atrapados;
            edad = ((Super) modeloLISTA.get(
                    jl_xmen.getSelectedIndex())).
                    getEdad();

            nombre = ((Super) modeloLISTA.get(
                    jl_xmen.getSelectedIndex())).
                    getNombre();
            atrapados = ((Super) modeloLISTA.get(
                    jl_xmen.getSelectedIndex())).
                    getAtrapados();
            planeta = ((Super) modeloLISTA.get(jl_xmen.getSelectedIndex())).getPlaneta();
            altura = ((Super) modeloLISTA.get(jl_xmen.getSelectedIndex())).getAltura();

            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().
                        equals("X-men")) {
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new Super(nombre, edad, planeta, altura, atrapados)
                            );
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;
                } //fin if
            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode("X-men");
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Super(nombre, edad, planeta, altura, atrapados)
                        );
                n.add(p);
                raiz.add(n);
            }  // fin if          
            modeloARBOL.reload();
        }
    }//GEN-LAST:event_jm_agregarActionPerformed

    private void jm_agregararbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_agregararbolActionPerformed
        // TODO add your handling code here:
        if (jl_vengadores.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL
                    = (DefaultTreeModel) jt_heroes.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloARBOL.getRoot();

            //obtener la persona a guardar
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_vengadores.getModel();
            String planeta, nombre, altura;
            int edad, atrapados;
            edad = ((Super) modeloLISTA.get(
                    jl_vengadores.getSelectedIndex())).
                    getEdad();

            nombre = ((Super) modeloLISTA.get(
                    jl_vengadores.getSelectedIndex())).
                    getNombre();
            atrapados = ((Super) modeloLISTA.get(
                    jl_vengadores.getSelectedIndex())).
                    getAtrapados();
            planeta = ((Super) modeloLISTA.get(jl_vengadores.getSelectedIndex())).getPlaneta();
            altura = ((Super) modeloLISTA.get(jl_vengadores.getSelectedIndex())).getAltura();

            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().
                        equals("Vengador")) {
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new Super(nombre, edad, planeta, altura, atrapados)
                            );
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;
                } //fin if
            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode("Vengador");
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Super(nombre, edad, planeta, altura, atrapados)
                        );
                n.add(p);
                raiz.add(n);
            }  // fin if          
            modeloARBOL.reload();
        }
    }//GEN-LAST:event_jm_agregararbolActionPerformed

    private void jl_darkavengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_darkavengerMouseClicked
        // TODO add your handling code here:
         if (jl_darkavenger.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_dark.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_darkavengerMouseClicked

    private void jl_sinistersixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_sinistersixMouseClicked
        // TODO add your handling code here:
         if (jl_sinistersix.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_sinister.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_sinistersixMouseClicked

    private void jm_eliminardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_eliminardActionPerformed
        // TODO add your handling code here:
                if (jl_darkavenger.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) jl_darkavenger.getModel();
            modelo.remove(jl_darkavenger.getSelectedIndex());
            jl_darkavenger.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");
        }
    }//GEN-LAST:event_jm_eliminardActionPerformed

    private void jm_eliminarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_eliminarsActionPerformed
        // TODO add your handling code here:
                if (jl_sinistersix.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) jl_sinistersix.getModel();
            modelo.remove(jl_sinistersix.getSelectedIndex());
            jl_sinistersix.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");
        }
    }//GEN-LAST:event_jm_eliminarsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAB5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAB5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAB5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAB5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAB5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_grupo;
    private javax.swing.JComboBox<String> cb_villano;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton jb_agregarpoder;
    private javax.swing.JButton jb_agregarpoder1;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JButton jb_salirpoder;
    private javax.swing.JButton jb_salirpoder1;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JDialog jd_poder;
    private javax.swing.JDialog jd_poderv;
    private javax.swing.JList<String> jl_darkavenger;
    private javax.swing.JList<String> jl_sinistersix;
    private javax.swing.JList<String> jl_vengadores;
    private javax.swing.JList<String> jl_xmen;
    private javax.swing.JMenuItem jm_agregar;
    private javax.swing.JMenuItem jm_agregararbol;
    private javax.swing.JMenuItem jm_agregard;
    private javax.swing.JMenuItem jm_agregars;
    private javax.swing.JMenuItem jm_el;
    private javax.swing.JMenuItem jm_eliminar;
    private javax.swing.JMenuItem jm_eliminard;
    private javax.swing.JMenuItem jm_eliminars;
    private javax.swing.JTree jt_heroes;
    private javax.swing.JTree jt_villanos;
    private javax.swing.JPopupMenu popup_dark;
    private javax.swing.JPopupMenu popup_eliminar;
    private javax.swing.JPopupMenu popup_eliminar2;
    private javax.swing.JPopupMenu popup_sinister;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_edad1;
    private javax.swing.JSpinner sp_muertes;
    private javax.swing.JTextArea ta_descrip;
    private javax.swing.JTextArea ta_descrip1;
    private javax.swing.JTextField tf_acrcel;
    private javax.swing.JTextField tf_altura;
    private javax.swing.JTextField tf_altura1;
    private javax.swing.JTextField tf_moratl;
    private javax.swing.JTextField tf_moratl1;
    private javax.swing.JTextField tf_nivel;
    private javax.swing.JTextField tf_nivel1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JTextField tf_planeta;
    private javax.swing.JTextField tf_planeta1;
    private javax.swing.JButton tf_poder;
    private javax.swing.JButton tf_poder1;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
}
